// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGe7hDNHy22Wzcyrj9CyYEy2XLfI9Kmss',
    appId: '1:689871710203:web:672d10b06cf2746fbe8d5e',
    messagingSenderId: '689871710203',
    projectId: 'icthub2024-9-fb543',
    authDomain: 'icthub2024-9-fb543.firebaseapp.com',
    storageBucket: 'icthub2024-9-fb543.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3HeGlAUdiKm6cF06B4RYacsxM4ggmKOM',
    appId: '1:689871710203:android:08fd9d98f266b8f3be8d5e',
    messagingSenderId: '689871710203',
    projectId: 'icthub2024-9-fb543',
    storageBucket: 'icthub2024-9-fb543.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAp-anza8yhpYZBoGBFdgN2jwKPE6D3pVc',
    appId: '1:689871710203:ios:e6565d56e6c69b02be8d5e',
    messagingSenderId: '689871710203',
    projectId: 'icthub2024-9-fb543',
    storageBucket: 'icthub2024-9-fb543.appspot.com',
    iosBundleId: 'com.example.task1',
  );
}
